# Generated by Django 5.2.6 on 2026-06-08 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "price_per_credit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("sold", "Sold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carbon_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("eastlands", "Eastlands"),
                            ("cbd", "CBD"),
                            ("westlands", "Westlands"),
                            ("karen", "Karen"),
                            ("rongai", "Rongai"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("recycling", "Recycling"),
                            ("reforestation", "Reforestation"),
                            ("energy", "Renewable Energy"),
                            ("education", "Education"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("tagline", models.CharField(max_length=200)),
                ("verified", models.BooleanField(default=False)),
                ("points", models.IntegerField(default=0)),
                ("members_count", models.IntegerField(default=1)),
                ("credits", models.IntegerField(default=0)),
                (
                    "diverted_kg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "energy_kwh",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "lead_applicant_uid",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_communities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Redemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reward_name", models.CharField(max_length=100)),
                ("tokens_spent", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="success",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firebase_uid",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("tokens_balance", models.IntegerField(default=0)),
                ("carbon_credits", models.IntegerField(default=0)),
                (
                    "household_id",
                    models.CharField(default="ZW-2026-0000", max_length=50),
                ),
                (
                    "total_waste_recycled",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_energy_generated",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("trees_planted", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WasteCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("organic", "Organic"),
                            ("e-waste", "E-waste"),
                            ("recyclables", "Recyclables"),
                            ("agriculture", "Agriculture"),
                        ],
                        max_length=50,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "energy_generated",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tokens_earned", models.IntegerField()),
                ("hub_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Empty", "Empty"),
                            ("Pre-Occupied", "Pre-Occupied"),
                            ("Fully Occupied", "Fully Occupied"),
                        ],
                        default="Empty",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunityMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("role", models.CharField(default="Member", max_length=50)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="ZeroWave_app.community",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("community", "user")},
            },
        ),
    ]
