# Generated by Django 5.2.6 on 2026-06-08 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ZeroWave_app", "0002_impactcampaign"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="region",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Individual User"),
                    ("bank", "Waste Collection Bank"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="wastecollection",
            name="category",
            field=models.CharField(
                choices=[
                    ("organic", "Organic"),
                    ("e-waste", "E-waste"),
                    ("recyclables", "Recyclables"),
                    ("agriculture", "Agriculture"),
                    ("metal", "Metal Waste"),
                    ("pharma", "Pharma Waste"),
                    ("plastic", "Plastic Waste"),
                    ("paper", "Paper Waste"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="WasteRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("organic", "Organic"),
                            ("e-waste", "E-waste"),
                            ("recyclables", "Recyclables"),
                            ("agriculture", "Agriculture"),
                            ("metal", "Metal Waste"),
                            ("pharma", "Pharma Waste"),
                            ("plastic", "Plastic Waste"),
                            ("paper", "Paper Waste"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "quantity_required",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "quantity_collected",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("tokens_per_kg", models.IntegerField(default=10)),
                ("status", models.CharField(default="Active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
