# Generated by Django 5.2.6 on 2026-06-08 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ZeroWave_app", "0003_userprofile_bank_name_userprofile_region_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("organic", "Organic"),
                            ("e-waste", "E-waste"),
                            ("recyclables", "Recyclables"),
                            ("agriculture", "Agriculture"),
                            ("metal", "Metal Waste"),
                            ("pharma", "Pharma Waste"),
                            ("plastic", "Plastic Waste"),
                            ("paper", "Paper Waste"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "estimated_weight",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("eastlands", "Eastlands"),
                            ("cbd", "CBD"),
                            ("westlands", "Westlands"),
                            ("karen", "Karen"),
                            ("rongai", "Rongai"),
                        ],
                        max_length=50,
                    ),
                ),
                ("address", models.TextField()),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Pickup"),
                            ("assigned", "Assigned"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_pickups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
