# Generated by Django 5.2.6 on 2026-06-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ZeroWave_app", "0004_collectionticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionticket",
            name="region",
            field=models.CharField(
                choices=[
                    ("delhi", "Delhi NCR"),
                    ("mumbai", "Mumbai Metro"),
                    ("bengaluru", "Bengaluru"),
                    ("hyderabad", "Hyderabad"),
                    ("chennai", "Chennai"),
                    ("kolkata", "Kolkata"),
                    ("pune", "Pune"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="region",
            field=models.CharField(
                choices=[
                    ("delhi", "Delhi NCR"),
                    ("mumbai", "Mumbai Metro"),
                    ("bengaluru", "Bengaluru"),
                    ("hyderabad", "Hyderabad"),
                    ("chennai", "Chennai"),
                    ("kolkata", "Kolkata"),
                    ("pune", "Pune"),
                ],
                max_length=50,
            ),
        ),
    ]
